### ISSUE TITLE
Not compile in XCODE 9.3 Beta 

### ISSUE THREAD

**Issue by truepatch** [libobjc/SGPlayer#58]
demo.xcworkspace

**Xcode 9.3 Error log:**
Undefined symbols for architecture x86_64:
  "_OBJC_IVAR_$_SGFFAVYUVVideoFrame.channel_pixels", referenced from:
      -[SGGLTextureYUV420 updateTextureWithGLFrame:aspect:] in SGPlayer(SGGLTextureYUV420.o)
  "_OBJC_CLASS_$_SGFFAVYUVVideoFrame", referenced from:
      objc-class-ref in SGPlayer(SGGLFrame.o)
  "_OBJC_CLASS_$_SGFFCVYUVVideoFrame", referenced from:
      objc-class-ref in SGPlayer(SGGLFrame.o)
  "_OBJC_CLASS_$_SGFFPlayer", referenced from:
      objc-class-ref in SGPlayer(SGPlayerImp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Xcode 9.1 :** This project compile!

**Comment by iamvijay** [comment]
Hi, any solution for this, Facing the same issue!

**Comment by fukemy** [comment]
same issue here
